### ISSUE TITLE
Target class does not exist.

### ISSUE THREAD

**Issue by anantgrafix** [laravel-at/laravel-image-sanitize#11]
Error in Laravel 7
"laravel-at/laravel-image-sanitize": "^1.3",

Error:
**Target class [App\Http\ImageSanitizeMiddleware] does not exist.**

controller namespace: `namespace App\Http\Controllers\User;`

route file: user.php
Route Binding:
`
protected function mapUserRoutes()
    {
        Route::prefix('user')
            ->middleware('web')
            ->namespace('App\Http\Controllers\User')
            ->group(base_path('routes/user.php'));
    }
`

Tried:
1. with web.php
2. with default namespace & location for controller

**Comment by mathiasonea** [comment]
did you register the middleware correctly in your Kernel.php?

```php
protected $routeMiddleware = [
    // ...
    'image-sanitize' => ImageSanitizeMiddleware::class,
];
```

And make sure you either import the class at the top of Kernel.php

```php
use LaravelAt\ImageSanitize\ImageSanitizeMiddleware;
```

or use the Fully Qualified Class Name

```php
protected $routeMiddleware = [
    // ...
    'image-sanitize' =>  \LaravelAt\ImageSanitize\ImageSanitizeMiddleware::class,
];
```

**Comment by anantgrafix** [comment]
'image-sanitize' =>  \LaravelAt\ImageSanitize\ImageSanitizeMiddleware::class,

This is working. Thank you.
