### ISSUE TITLE
Need Support for Laravel 10

### ISSUE THREAD

**Issue by phil-cto** [laravel-at/laravel-image-sanitize#20]
Need Support for Laravel 10 and PHPunit 10

**Comment by mazedlx** [comment]
Feel free to open up a PR.

**Comment by su-rowel** [comment]
I added a PR here: https://github.com/laravel-at/laravel-image-sanitize/pull/19

**Comment by nuernbergerA** [comment]
Hey @su-rowel

sorry for the long delay - i tagged a new release.

please close the issue if all went well.

cheers
adrian
