### ISSUE TITLE
Laravel 7.* support

### ISSUE THREAD

**Issue by barbosa89** [laravel-at/laravel-image-sanitize#8]
Thanks, bro, this package is powerful.

**Comment by nuernbergerA** [comment]
Thanks @barbosa89!

I tagged a new [release](https://github.com/laravel-at/laravel-image-sanitize/releases/tag/v1.2.0) with `Laravel 7.x` support.

Have fun with it!

**Comment by barbosa89** [comment]
Thanks @nuernbergerA, great
